### ISSUE TITLE
Nothing happened when pressing link in toolbar

### ISSUE THREAD

**Issue by vinodsnayvik** [imnapo/react-native-cn-quill#120]
Hi,
I'm adding link in QuillToolbar options but when I'm clicking on it then nothing is happening. i tried to get html using onHtmlChange when we made selection it is making anchor tag but there is not way to add link.

Am i missing something ?

**Comment by dimaokk** [comment]
> Hi, I'm adding link in QuillToolbar options but when I'm clicking on it then nothing is happening. i tried to get html using onHtmlChange when we made selection it is making anchor tag but there is not way to add link.
> 
> Am i missing something ?
have you decided this problem?

**Comment by vinodsnayvik** [comment]
I checked on the official documentation and found that you have to select text and then link on link but not working on my side. So I implemented a custom method to get link and put in editor.

**Comment by kalmahik** [comment]
> I checked on the official documentation and found that you have to select text and then click on link but not working on my side. So I implemented a custom method to get link and put in editor.

Hey! Can you share your solution here pls? 🙏
