### ISSUE TITLE
Is it ready for use?

### ISSUE THREAD

**Issue by RanderGabriel** [imnapo/react-native-cn-quill#18]
Hi! Thank you for you great work on this library!

I would like to know if it is ready to use already. We are currently using the imnapo/react-native-cn-richtext-editor. Do you recommend migrating it to this new version?

**Comment by imnapo** [comment]
Hi @RanderGabriel , yes you may use it, as it is covering most of the react-native-cn-richtext-editor right now. 
there are some tasks that we are working on to complete most of Quill Api features, you may find  them here in issues section of library. 
feel free to reopen this issue or create new one if you have further questions or bugs.
