### ISSUE TITLE
Is there a way to set the HTML contents of the editor?

### ISSUE THREAD

**Issue by evrimfeyyaz** [imnapo/react-native-cn-quill#25]
Similar to `getHtml()`, is there way to set the HTML contents of the editor?

**Comment by imnapo** [comment]
There is a  [InitialHtml](https://github.com/imnapo/react-native-cn-quill#initialhtml) for initialization. and `setContent` which works with Quill [Delta datatype](https://quilljs.com/docs/delta/). Currently, there isn't `setHtml `option but We'll try to implement it.

**Comment by imnapo** [comment]
@evrimfeyyaz,  we've added [dangerouslyPasteHTML](https://github.com/imnapo/react-native-cn-quill#dangerouslypastehtmlindex-number-html-string). You may use it now for release `>= 0.7.0`

**Comment by imnapo** [comment]
Please feel free to open it again or create a new one and reference this if you have further questions.

**Comment by evrimfeyyaz** [comment]
Thanks @imnapo.
