### ISSUE TITLE
import3rdParties

### ISSUE THREAD

**Issue by eran88** [imnapo/react-native-cn-quill#31]
Is there is a way to add a css file to the webview?
I can see the import3rdParties prop but where can I add the name of the file?

**Comment by imnapo** [comment]
Hi @eran88 , No there isn't a way for now. there is a issue #3 to pass custom styles and we will implement it in future releases. `import3rdParties ` is related to editor's own 3rd party libraries like quill's scripts and styles.

**Comment by imnapo** [comment]
We've added [customStyles](https://github.com/imnapo/react-native-cn-quill#customStyles).  You may use it in release `>= 0.7.0`
