### ISSUE TITLE
onTextChange doesn't return the current html data

### ISSUE THREAD

**Issue by eran88** [imnapo/react-native-cn-quill#32]
Is there any way to get the current html data on the onTextChange event?

**Comment by imnapo** [comment]
`onTextChange ` like quill's native [`textChange`](https://quilljs.com/docs/api/#text-change) event returns `Delta` object types. you may call `getHtml` for a html string. Or we may change `onTextChange` in future releases to return html as well.

**Comment by imnapo** [comment]
We've added [onHtmlChange](https://github.com/imnapo/react-native-cn-quill#onhtmlchange).  You may use it in release `>= 0.7.0`

**Comment by imnapo** [comment]
Please feel free to open it again (@eran88) or create a new one and reference this if you have further questions.
