### ISSUE TITLE
Options aren't getting selected

### ISSUE THREAD

**Issue by avinashyalgonde** [imnapo/react-native-cn-quill#37]
Selecting options from toolbar not working. When clicked colour options it displays popup with defined colours but no colour gets selected. Whats the issue here?

**Comment by imnapo** [comment]
Do you have this issue with all items that have options to select or just with color?
Please post your code here to be able to help you.

**Comment by avinashyalgonde** [comment]
@imnapo Thanks for reply. Issue is resolved now. I can be able to select and apply the options

**Comment by arunim2405** [comment]
@avinashyalgonde how did you solve it?
