### ISSUE TITLE
Header tag not getting cleared

### ISSUE THREAD

**Issue by avinashyalgonde** [imnapo/react-native-cn-quill#39]
If we start with blank editor and if we select H1 or H2 option, then even after clearing editor H1 or H2 tag won't get disabled/cleared.

**Comment by imnapo** [comment]
@avinashyalgonde,  If I understood right you mean when you select H1 and start typing then if you clear what you typed, its still H1 selected (if you start typing again it's with H1 style)?
I think most Editors have same behavior as you explained. This editor is based on `Quill Js` and you may see same thing [here in it's playground](https://quilljs.com/). 
I've also checked MS Word and clearing all content doesn't remove last selected style (Like H1 you said) there either.

**Comment by avinashyalgonde** [comment]
How do I disable that? Because selecting same option again isn't disabling the tag. I tried though.

**Comment by imnapo** [comment]
@avinashyalgonde , I've checked it with iPhone device and it worked as expected (selecting same option again is disabling the tag). Could you please specify more details on this issue like what device you are using?
