### ISSUE TITLE
Android app crash on adding two instance on same screen

### ISSUE THREAD

**Issue by avinashyalgonde** [imnapo/react-native-cn-quill#40]
I tried adding editors two times with different references on single screen but app is crashing on Android real device. Can you please help me to resolve this?

**Comment by avinashyalgonde** [comment]
@imnapo Is it possible to add multiple instance on same screen? Please help me out

**Comment by imnapo** [comment]
@avinashyalgonde Please post your code here to be able to help you.

**Comment by avinashyalgonde** [comment]
In view added this piece of code

let RichText = useRef();
let toolbar = [
    [{ header: '1' }, { header: '2' }],
    [{ size: [] }],
    ['bold', 'italic', 'underline', 'strike', 'blockquote'],
    [{ list: 'ordered' }, { list: 'bullet' }, { indent: '-1' }, { indent: '+1' }],
    ['link'],
    ['clear']
];

<ScrollView
            style={{
              width: '100%',
              backgroundColor: 'red',
              borderColor: 'black',
              borderWidth: 1,
            }}
            contentContainerStyle={{
              justifyContent: 'center',
              marginLeft: -1,
              marginTop: -1,
            }}
          >
            <QuillToolbar editor={RichText} options={toolbar} theme="light" />
          </ScrollView>
          <QuillEditor
            theme={{ placeholder: 'Enter Description' }}
            style={{
              maxHeight: 150,
              minHeight: 150,
              width: width - 80,
              padding: 0,
              borderColor: 'gray',
              borderWidth: 1,
              backgroundColor: 'white',
            }}
            customStyles={['padding: 0']}
            ref={RichText}
            onHtmlChange={text => setDescription(text.html)}
            initialHtml={description}
          />

**Comment by avinashyalgonde** [comment]
**android:hardwareAccelerated="false"** is what I needed to fix crash causing on Android after adding couple of instances on editor. Thanks.
