### ISSUE TITLE
Insert local image from device gallery?

### ISSUE THREAD

**Issue by 7dp** [imnapo/react-native-cn-quill#42]
Any suggestion on how to do that?

Thanks for this great library.

**Comment by rd1999** [comment]
@imnapo I'm unable to insert image from local device. Can you tell me how to do that?

**Comment by lylest** [comment]
facing the same problem if I click the image icon and nothing happens on the toolbar nothing happens

**Comment by rd1999** [comment]
@lylest I have implemented it through external button and added the insertEmbed function to it. It is working but I'm not able to insert image from local device. This function is only working if I add http/https url

it is working - 
insertImage(path) {
         _editor.current.insertEmbed(10, 'image', 'https://quilljs.com/images/cloud.png');
}

it is not working - 
insertImage(path) {
         _editor.current.insertEmbed(10, 'image', path);
}
where path is the path to a local image file

**Comment by rd1999** [comment]
I have got a solution for inserting local images from device.
You can upload the local file in firebase storage and they provide a download url which can be used to insert the image.

Example - 
async getAlert(uri, name, firebasePath){
            const imageRef = storage().ref(`${firebasePath}/${name}`)
            await imageRef.putFile(uri, { contentType: 'image/jpg'}).catch((error) => { throw error })
            const url = await imageRef.getDownloadURL().catch((error) => { throw error });
            _editor.current.insertEmbed(10, 'image', url);
}

This function can be called by 
await uploadImage('uri/of/local/image', 'imageName.jpg', 'path/to/remote/folder');

**Comment by imnapo** [comment]
Hi Guys, It seems that it's related to permissions and react-native-web-view. I'll try to find a solution and update it here. 
For now you may convert it to base64 ( `src="data:image/png;base64,${imageData}` ) or use external sources like firebase as mentioned above.

**Comment by 7dp** [comment]
It's work pretty cool, thanks @imnapo
