### ISSUE TITLE
How to dynamically assign a container height based on content.

### ISSUE THREAD

**Issue by Nilesh8451** [imnapo/react-native-cn-quill#43]
Can anyone tell me how to assign the container height based on the content of html. Because of fixed height it not looking nice and also not scrolling. It's very hard scrolling 

For me I want height container should change dynamically I assign html content. When I scroll it should scroll whole screen not container

**Comment by FabianMeul** [comment]
Hey @Nilesh8451 

I added this feature in https://github.com/imnapo/react-native-cn-quill/pull/66.
