### ISSUE TITLE
Adding setSelection handler or let android break a line without space

### ISSUE THREAD

**Issue by beebzo** [imnapo/react-native-cn-quill#46]
Hi! Nice module! It plays a significant role in my app, so I know it almost inside out.
I have an issue - when I press enter to start a new line, a new line is created, but my focus is still on the old one. Also, letters become capital for a second, but then become small again. The only way to change a line without hiding a keyboard is to press space, which is not very convenient. It would be great if you fixed it:) But if it's rare, I can do it by myself, for doing that I need a setSelection handler which is not included here. The problem is only on android.
I also have another issue with android - while using toolbar component and tapping elsewhere there except for bullet or ordered lists (for example "bold" button) I always lose keyboard focus, so the only way to format the text is to select it.

**Comment by imnapo** [comment]
#12

**Comment by imnapo** [comment]
`setSelection` is added in new release v0.7.10 . you may find documentations [here](https://github.com/imnapo/react-native-cn-quill#setselectionindex-number-length-number--0-source-string--api).
I'm closing this issue now, Feel free to reopen if the problem still exists.
