### ISSUE TITLE
Please fix the release version of 0.7.9

### ISSUE THREAD

**Issue by LOMFM** [imnapo/react-native-cn-quill#60]
After install this version, I've got 2 errors totally.

- Icon module not found issue.
assets/icons/align-left.png ...

- List Tool Button not found issue
text-list-button.tsx not found from tool-set.tsx

I have resolved this with following.
Copy the files (assets and text-list-button.tsx) from 0.7.1 version to 0.7.9

So you have to fix this version with containing those file.
Thanks.

**Comment by imnapo** [comment]
hi @LOMFM , I've checked the new release , It work as expected and there is no error. I think it's related to `npm cache` of your system. both 2 files you mention are no longer needed in the package.

- Icons and assets folder are removed and replaced with `base64` images (check [here](https://github.com/imnapo/react-native-cn-quill/blob/master/src/constants/icons.ts)).
- text-list-button is renamed with list-button, tool-set is not using text-list-button as you may see in [here](https://github.com/imnapo/react-native-cn-quill/blob/master/src/toolbar/components/tool-set.tsx)

**Comment by LOMFM** [comment]
Okay. I will clean the cache and check this again.
