### ISSUE TITLE
I can not set placeholder

### ISSUE THREAD

**Issue by phongnguyenmaster** [imnapo/react-native-cn-quill#89]
why is it like that?
**placeholder: quill.placeholder,**
=> **placeholder: this.props.placeholder,**

    return createHtml({
      initialHtml,
      autoSize: this.props.autoSize,
      placeholder: quill.placeholder,
      theme: quill.theme ? quill.theme : 'snow',
      toolbar: JSON.stringify(quill.modules?.toolbar),
      clipboard: quill.modules?.clipboard,
      keyboard: quill.modules?.keyboard,
      libraries: import3rdParties,
      editorId: quill.id ? quill.id : 'editor-container',
      defaultFontFamily,
      containerId,
      color: theme.color,
      fonts: customFonts,
      backgroundColor: theme.background,
      placeholderColor: theme.placeholder,
      customStyles,
      customJS,
    });

**Comment by farazreact** [comment]
issue is till there
